name: "standalone_leading_jet_regression"
description: "Standalone DNN regression for leading jet pT prediction"
version: "1.0"
created_by: "Liangyu"


dataset:
  catalog_limit: 20
  include_labels: true
  plot_distributions: true
  run_numbers: !python get_run_numbers()[-2:]  # ATLAS run numbers to process
  shuffle_buffer: 50000
  signal_keys: ["zprime_tt", "wprime_taunu", "DMA", "leptoquark", "dm_4top_scalar"]  # Signal types for anomaly detection
  test_fraction: 0.15
  validation_fraction: 0.15

evaluation:
  create_detailed_plots: true
  error_analysis_bins: 100
  fixed_epochs: 30
  include_feature_importance: false
  prediction_sample_size: 1000
  regression_data_sizes:
  - 1000
  - 2000
  - 5000
models:
  standalone_dnn:
    architecture:
      activation: relu
      hidden_layers:
      - 128
      - 128
      - 64
      - 48
      - 32
      name: example_regressor
      output_activation: linear
    hyperparameters:
      batch_normalization: true
      dropout_rate: 0.2
      l2_regularization: 0.001
    model_type: standalone_dnn_regressor
name: example_standalone_regression
pipeline:
  delete_catalogs: false
  experiments_output_dir: _standalone_experiments
task:
  event_filters: {}
  input_array_aggregators:
  - filter_branches:
    - branch: InDetTrackParticlesAuxDyn.d0
      max: 5.0
      min: -5.0
    - branch: InDetTrackParticlesAuxDyn.z0
      max: 100.0
      min: -100.0
    input_branches:
    - InDetTrackParticlesAuxDyn.d0
    - InDetTrackParticlesAuxDyn.z0
    - InDetTrackParticlesAuxDyn.phi
    - derived.InDetTrackParticlesAuxDyn.eta
    - derived.InDetTrackParticlesAuxDyn.pt
    - derived.InDetTrackParticlesAuxDyn.reducedChiSquared
    max_length: 20
    min_length: 5
    sort_by_branch:
      branch: InDetTrackParticlesAuxDyn.qOverP
  input_features: []
  label_array_aggregators:
  - - filter_branches:
      - branch: AnalysisJetsAuxDyn.pt
        min: 20.0
      input_branches:
      - AnalysisJetsAuxDyn.pt
      max_length: 1
      min_length: 1
      sort_by_branch:
        branch: AnalysisJetsAuxDyn.pt
  label_features:
  - []
training:
  standalone_dnn:
    batch_size: 512
    early_stopping:
      min_delta: 0.0001
      patience: 15
    epochs: 50
    gradient_clip_norm: 1.0
    learning_rate: 0.001
    lr_scheduler:
      factor: 0.5
      min_lr: 1.0e-06
      monitor: val_loss
      patience: 8
      type: reduce_on_plateau
      verbose: true
    plot_training: true
