dataset_id: dataset_runs00296939_00296942_00297447_tracks56_0c68f1d7
creation_date: '2025-02-03 22:08:36.210624'
config:
  run_numbers:
  - 00296939
  - 00296942
  - 00297447
  track_selections:
    eta:
    - -2.5
    - 2.5
    chi2_per_ndof:
    - 0.0
    - 10.0
  event_selections: {}
  max_tracks_per_event: 56
  min_tracks_per_event: 3
  catalog_limit: 5
  train_fraction: 0.7
  validation_fraction: 0.15
  test_fraction: 0.15
  batch_size: 128
  shuffle_buffer: 50000
  dataset_id: null
  dataset_path: null
  creation_date: null
  atlas_version: null
  software_versions: null
  normalization_params: null
atlas_version: 1.0.0
software_versions:
  python: 3.9.21
  numpy: 1.24.3
  tensorflow: 2.13.1
  h5py: 3.12.1
