_source_config_file: /pscratch/sd/l/liangyu/hep_foundation/test_standalone.yaml
created_by: Liangyu
dataset:
  catalog_limit: 2
  include_labels: true
  plot_distributions: true
  run_numbers:
  - 00311481
  shuffle_buffer: 1000
  signal_keys:
  - zprime_tt
  test_fraction: 0.2
  validation_fraction: 0.2
description: Quick test of standalone DNN regression pipeline
evaluation:
  create_detailed_plots: true
  error_analysis_bins: 50
  fixed_epochs: 5
  include_feature_importance: false
  prediction_sample_size: 500
  regression_data_sizes:
  - 500
  - 1000
models:
  standalone_dnn:
    architecture:
      activation: relu
      hidden_layers:
      - 64
      - 32
      name: simple_test_regressor
      output_activation: linear
    hyperparameters:
      batch_normalization: true
      dropout_rate: 0.1
      l2_regularization: 0.0
    model_type: standalone_dnn_regressor
name: simple_test_standalone
pipeline:
  delete_catalogs: false
  experiments_output_dir: _standalone_experiments
task:
  event_filters: {}
  input_array_aggregators:
  - filter_branches:
    - branch: InDetTrackParticlesAuxDyn.d0
      max: 5.0
      min: -5.0
    input_branches:
    - InDetTrackParticlesAuxDyn.d0
    - InDetTrackParticlesAuxDyn.z0
    - InDetTrackParticlesAuxDyn.phi
    - derived.InDetTrackParticlesAuxDyn.eta
    - derived.InDetTrackParticlesAuxDyn.pt
    max_length: 30
    min_length: 10
    sort_by_branch:
      branch: derived.InDetTrackParticlesAuxDyn.pt
  input_features: []
  label_array_aggregators:
  - - filter_branches:
      - branch: AnalysisJetsAuxDyn.pt
        min: 20.0
      input_branches:
      - AnalysisJetsAuxDyn.pt
      max_length: 1
      min_length: 1
      sort_by_branch:
        branch: AnalysisJetsAuxDyn.pt
  label_features:
  - []
training:
  standalone_dnn:
    batch_size: 256
    early_stopping:
      min_delta: 0.001
      patience: 3
    epochs: 10
    gradient_clip_norm: 1.0
    learning_rate: 0.001
    lr_scheduler:
      factor: 0.7
      min_lr: 1.0e-05
      monitor: val_loss
      patience: 2
      type: reduce_on_plateau
      verbose: true
    plot_training: true
version: '1.0'
